# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'campfeed' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for campfeed

  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Messaging'

  target 'campfeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'campfeed-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for campfeed-tvOS

  target 'campfeed-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
